---
  root: true
  extends:
    - airbnb
  rules:
    max-len: off
    react/jsx-fragments: warn # ESDoc is not compatible with jsx fragments
    max-classes-per-file: warn
    valid-jsdoc:
      - warn
      -
        requireParamDescription: false
        requireReturn: false
        requireReturnDescription: false
