sudo: required
language: node_js
services:
  - docker
node_js:
  - "12.13.0"
cache:
  directories:
    - node_modules
env:
  global:
    # CC_TEST_REPORTER_ID
    - secure: "aBlxCcn2sS8J1Y3W9heWLXKQUyK/w4ebydk85EnW9cytQh71rYucyvdRKLx+/d5nqkgstCVd3YQS/qneEEl0XRn5py9j5eI1n25VtlMbotOoQ2GTeXBsx83ij6di1WjuPUk3EAqDy29Hess/nlxAYiSItkC7si4TWXRqlSgC9gMaB3g2twLLuzrtC6YXCPGnALnFwH9Ie7JyRpPccSrguZIVRm7boDmdeAfs4mohkgoujKYkSNMzKgIaDs+QdHD9Q9+80Nw+rkfEJowI4u6kZWnGZENqr6ZacmOV0gXKdHgATsriMMgasA91E8+VCnBvRWU6hru5orfjWBQMRVSQcanIHhKAC32axUKWwN1BrfzIZAai1Jeh0JvbHiBg1O9cmUhmXTtZvEhCZF8M5/xJmuB14yAT40MHvJOeSmU8PesRHFUlbQ32kgkMtavbYPJGKcnc+3dwvK8cN5M7SCxTJG0EB1SWj0RsvriFD3nbi/mWaZLZCXUvZ7QtqTxFwcehylF7WN66NlXmLnmd83EMVaOTQJ6aO+pcrzWAgNklK8cOaqHcp9aEAl2iKK/ENwZGE4OwG9YuCDa3jcFZYPgAizdFURJuGAw8Q9nXi5yavb5nBwzIMN3jBGo0DVL5UMN2U3g3V2wqnDGdMjgkt03owctYDws17j6lz9FExYzFixs="
    - AWS_ACCESS_KEY_ID=AKIAI7GXDJMDI4AHQ6HA
    # AWS_SECRET_ACCESS_KEY
    - secure: "3FbeNtgfhu3WFzoC2JZthOgrE/Oh9c4xMOBtS1NZ72rro2vuVVjY5wvwN9aPib/qRpLt9qndI71kttgobUOhTWOJVt6tfYn3/+DjDBnPXOUhLRp2tMi5MhbRY4pRzqQqrGEwj6U6LnUd9uB/164P6pvhfArvCFtcF/g3Zv3wcYIRP9Ett7VMNIoqRzLxPCryF5iSEHlirlkciouYjNVSVknjg6yTvzmUvkqLqOYIfvdxI57HnkFrJhPFACD4REX9VTyxCuChyfl7vtqAeMWTipVf5DaanPS/U6cbymIeCB9pmq33xNi9TpyXh6WnDm2TJHZDfY8iN3znp9/NZkftp3/pT30psbcx20K7qQVV3b84+NfxVs8MVspiIIqPzL972H9b54tH3EMUMPymT46BsBvN2EQTEWw8/2tvZcAjJzdSQf0ZzCI5FL68SGk03AQ4nFBG/v1SRIKsGWTl0PH9uHHXrgtwtvjqL28M0yivSuBut+CCtfi26RZdnP+xDDahBcBG8EOLiQGx/PP99s2ItDgJ0L9SL6UXfyVIZY0mqdYkc6GJO8VvQsKjDb0axS4oKgXXcDbViPb6lqAiqdxq936nkG32PdqpxIiSD3DkwGugxy4tWphLEgKggQQ71/Qk94NgCxrQWru1I6hMKa/LxTv1xxmXI8l60SRDN1eH4QU="
    - AWS_DEFAULT_REGION=ap-northeast-1
    - ECS_CLUSTER=cattaz2
    - ECS_SERVICE=cattaz-ecs2-EcsService-1X471KVWUPJT1
    - ECS_REPO=cattaz
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - ./scripts/run-travis-tests.sh
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT # Rquires CC_TEST_REPORTER_ID
after_success:
  - ./node_modules/.bin/codecov # CODECOV_TOKEN is not required for Travis to test public repositories
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js # COVERALLS_SERVICE_NAME and COVERALLS_REPO_TOKEN env variables is not required for Travis
before_deploy:
  - sudo apt-get update
  - sudo apt-get install -y python-pip
  - sudo pip install awscli
  - aws --version
deploy:
  - provider: script
    on:
      branch: release
    script: ./scripts/deploy-to-aws-ecs.sh
