version: '2.1'
services:
  web:
    build:
      context: .
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        PORT: ${PORT:-8080}
    ports:
      - "${PORT:-8080}:8080"
