version: '2.1'
services:
  web:
    build:
      context: .
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        PORT_WEBSOCKET: ${PORT_WEBSOCKET:-1234}
    ports:
      - "${PORT_WEBSOCKET:-1234}:1234"
      - "${PORT_WEB:-8080}:8080"
